### ISSUE TITLE
Add correct precedence

### ISSUE THREAD

**Issue by chrisdreams13** [BorysLevytskyi/BitwiseCmd#9]
I entered this to your page and show me an incorrect value with the expression: 4|5<<1^8&9
your page shows me a zero, while the result is 6 because you need calculate in this order:
<<
&
^
|

**Comment by BorysLevytskyi** [comment]
Hey, Chris. Thanks for your input and sorry for the late reply. This tool uses javascript's `eval()` to calculate expressions. So the order is dictated by the javascript engine of your browser. For the sake of simplicity, I do not intend to change that any time soon. Closing this issue as By Design.
